### ISSUE TITLE
validate the schema first?

### ISSUE THREAD

**Issue by cKlee** [jorol/MARC-Schema#1]
Should the schema be validated before using it to validate the data?

1. Validate MARC schema against Avram
2. Validate MARC data

Otherwise you can not be sure, it is a valid [Avram](https://format.gbv.de/schema/avram)  instance.

**Comment by jorol** [comment]
Creating a [JSON Schema](http://json-schema.org/) for Avram and validating against it could be one way to do it. We should discuss that with @nichtich.

**Comment by nichtich** [comment]
There will be a JSON Schema but I would not require it in this module. Validating Avram Schemas is an independent task.

Am 13. Februar 2018 13:12:02 MEZ schrieb Johann Rolschewski <notifications@github.com>:
>Creating a [JSON Schema](http://json-schema.org/) for Avram and
>validating against it could be one way to do it. We should discuss that
>with @nichtich.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jorol/MARC-Schema/issues/1#issuecomment-365249135

-- 
Jakob Voß via Android

**Comment by cKlee** [comment]
@nichtich But the module depends on a valid schema. If the schema is not valid, the module might not recognize this and validates the document as valid. E.g. the module looks for a key in the schema and the key does not exist, because the schema is not valid. Then no rule can be applied and errors in the document are not detected.

**Comment by nichtich** [comment]
If you try to validate with a broken schema sure you get wrong results - this is known as [garbage in, garbage out](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out). To answer the initial questions: yes, a schema should be validated before using it. But I doubt this should be part of this module.

**Comment by cKlee** [comment]
@nichtich I see. Then the schema validation should be made in another module, and this module should use it to validate the schema.
