### ISSUE TITLE
`marcvalidate` comes with old MARC Version

### ISSUE THREAD

**Issue by TobiasNx** [jorol/MARC-Schema#10]
Hi @jorol,
I am not sure if this is the correct repo but the cli command `marcvalidate` comes with old marc schema. It complains about Marc Element `856 $$r` which was introduced 2022.

```
856	unknown subfield	r
oersi:aHR0cHM6Ly93d3cuaG9vdS5kZS9tYXRlcmlhbHMvYXJiZWl0c21hdGVyaWFsLXdlbGNoZXMtbGl0ZXJhdHVydmVyd2FsdHVuZ3Nwcm9ncmFtbS1pc3QtZnVyLW1pY2gtYW0tYmVzdGVuLWdlZWlnbmV0	856	unknown subfield	r
oersi:aHR0cHM6Ly9vZXIucHJlc3Nib29rcy5wdWIvaW5mb3JtZWRhcmd1bWVudHMv	856	unknown subfield	r
oersi:aHR0cHM6Ly9vZXIucHJlc3Nib29rcy5wdWIvaW5mb3JtZWRhcmd1bWVudHMv	856	unknown subfield	r
```

**Comment by jorol** [comment]
Thanks for the report. I use an Avram MARC schema from this project <https://github.com/pkiraly/qa-catalogue/blob/main/avram-schemas/marc-schema.json> for validation. I will ask @pkiraly to fix this and I make a new release for `marcvalidate` afterwards.

**Comment by jorol** [comment]
@pkiraly updated the schema file and I pushed a new version v.0.16 to CPAN, which should be available in some minutes. To install the new version run:

```
cpanm MARC::Schema

# or

cpan MARC::Schema 
```

Thanks again for reporting this issue.
